raise NameError('HiThere')

#
raise ValueError

#
try:
    raise NameError:
        print('An Exception flew by!')
    raise
